spring.application.name=corporate-carsharing

server.port=${PORT:8080}

spring.datasource.url=${DATABASE_URL}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.sql.init.mode=never

spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true

spring.jackson.time-zone=Europe/Madrid
spring.jpa.properties.hibernate.jdbc.time_zone=Europe/Madrid

spring.datasource.hikari.maximum-pool-size=2
spring.datasource.hikari.minimum-idle=0
spring.datasource.hikari.connection-timeout=10000
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.max-lifetime=600000